default:
    @just --list

build:
    cd util_packages && scryer-prolog -f pkg.pl -g "catch(pkg_install(_), _, halt(1)), halt"

test:
    #!/bin/sh
    set -eu

    exit_code=0

    for dir in test*/; do
        if (cd "$dir" && just test); then
            echo "Test in $dir passed"
        else
            echo "Test in $dir FAILED"
            exit_code=1
        fi
    done

    exit "$exit_code"
    