test: clean-install
    scryer-prolog -f main.pl -g "catch(main, _, halt(1)),halt"

clean:
    rm --recursive --force scryer_libs

install:
    scryer-prolog -f bakage.pl -g "catch(pkg_install(_), _, halt(1)),halt"

# This is so that we don't depend on the ordering of dependencies,
# which doesn't seem to be documented anywhere.
[doc]
clean-install: clean
    just install
