test:
    #!/bin/sh
    set -eu

    source ../util_packages/report_test.sh

    echo "Testing the installation of a git hash dependency"

    rm -rf scryer_libs && rm -f manifest-lock.pl
    scryer-prolog main.pl -g "catch(main, _, halt(1)) ."

    exitCode=0

    if [ ! -d "./scryer_libs/packages/test" ]; then
        exitCode=1
        print_test_result "the package folder exist in the dependencies" failure
    else
        print_test_result "the package folder exist in the dependencies" success
    fi

    if [ ! -f "./scryer_libs/packages/test/scryer-manifest.pl" ]; then
        exitCode=1
        print_test_result "the manifest of the dependency exist" failure
    else
        print_test_result "the manifest of the dependency exist" success
    fi

    dependencyGitHash=$(cd ./scryer_libs/packages/test && git rev-parse HEAD)

    if [ "$dependencyGitHash" != "d19fefc1d7907f6675e181601bb9b8b94561b441" ]; then
        exitCode=1
        print_test_result "the dependency is at the correct git commit hash" failure
    else
        print_test_result "the dependency is at the correct git commit hash" success
    fi

    rm -rf scryer_libs && rm -f manifest-lock.pl

    exit ${exitCode}