test: build
    #!/bin/sh
    set -eu

    exit_code=0

    for dir in test*/; do
        if (cd "$dir" && just test); then
            printf "%s\n" "Test in $dir passed"
        else
            printf "%s\n" "Test in $dir FAILED"
            exit_code=1
        fi
    done

    exit "$exit_code"

build:
    just util_packages/clean-build

clean:
    just util_packages/clean
