test:
    #!/bin/sh
    set -eu
    
    . ../utils/report_test.sh

    printf "%s\n" "Testing of all invalid dependencies"

    rm -rf scryer_libs && rm -f manifest-lock.pl

    scryer-prolog main.pl -g "catch(main, _, halt(1)) ."

    rm -rf scryer_libs && rm -f manifest-lock.pl
