test:
    #!/bin/sh
    echo "Testing the installation of a git branch dependency"
    set -eu
    
    rm -rf scryer_libs && rm -f manifest-lock.pl
    scryer-prolog main.pl -g "catch(main, _, halt(1)) ."
    rm -rf scryer_libs && rm -f manifest-lock.pl
